# Trial number:      137
# HOTA, MOTA, IDF1:  [55.567]
asso_func: giou
conf_thres: 0.9 #0.5122620708221085
delta_t: 1
det_thresh: 0
inertia: 0.2
iou_thresh: 0.3
max_age: 10
min_hits: 5
use_byte: False